#! /usr/bin/env node

require('dotenv').config({path: `${__dirname}/.env`});
const yargs = require('yargs/yargs');
const {hideBin} = require('yargs/helpers')
const argv = yargs(hideBin(process.argv))
    .default({size: '1024x768'})
    .demandOption(['room'])
    .describe('size', 'The size of recorded video(s)')
    .describe('room', 'The ID of the room to record')
    .describe('audioOnly', 'Pass this option if you\'d like to only record the audio of the given room').argv;

const axios = require('axios').create({
    headers: {
        Authorization: 'Bearer ' + process.env['ICE_API_TOKEN'],
        Accept: 'application/json'
    }
});
const {PassThrough} = require('stream');
const fs = require('fs');
const Websocket = require('ws');
const {RTCAudioSink, RTCVideoSink} = require('wrtc').nonstandard;
const {RTCPeerConnection, RTCIceCandidate, RTCSessionDescription} = require('wrtc');
const ffmpeg = require('fluent-ffmpeg');
const {StreamInput} = require('fluent-ffmpeg-multistream');

const VIDEO_OUTPUT_SIZE = argv.size;
const VIDEO_INPUT_DIR = `./storage/app/${argv.room}`;

let peers = {}, iceServers = [], signalingChannel;

function initSignalingChannel(){
    signalingChannel = new Websocket(`${process.env['PROTOCOL']}://${process.env['DOMAIN']}:${process.env['PORT']}${process.env['URL']}`);
    signalingChannel.onopen = () => {
        signalingChannel.send(JSON.stringify({
            action: 'record',
            room: argv.room
        }));
        setInterval(() => {
            signalingChannel.send(JSON.stringify({action: 'ping'}));
        }, 15000);
    };
    addSignalingListeners();
}

function addSignalingListeners(){
    signalingChannel.onmessage = (e) => {
        var message = JSON.parse(e.data);
        switch(message.action){
            case 'peer':
                if(peers[message.id] === undefined)
                    initRemotePeer(message);
                break;
            case 'answer':
                handleAnswer(message.answer, message.senderId)
                break;
            case 'candidate':
                handleCandidate(message.candidate, message.senderId);
                break;
            case 'disconnect':
                peerDisconnected(message.peer);
        }
    }
}

function handleAnswer(answer, peerId){
    let connection = peers[peerId].connection;
    if(!connection.remoteDescription)
        connection.setRemoteDescription(new RTCSessionDescription(answer)).then(() => addPendingCandidates(peerId));
}

function handleCandidate(candidate, senderId){
    let connection = peers[senderId].connection;
    if(!connection.remoteDescription)
        peers[senderId].pendingCandidates.push(candidate);
    else
        connection.addIceCandidate(new RTCIceCandidate(candidate)).catch(function(e){
            console.error('Could not add received ICE candidate', e);
        });
}

function addPendingCandidates(peerId){
    peers[peerId].pendingCandidates.forEach((candidate) => handleCandidate(candidate, peerId));
    peers[peerId].pendingCandidates = [];
}

function initRemotePeer(initMessage){
    let peerId = initMessage.id, audioOnly = argv.audioOnly || initMessage.audio_only || false;
    peers[peerId] = {
        audioOnly,
        connection: new RTCPeerConnection({iceServers}),
        pendingSdp: null,
        pendingCandidates: [],
        stream: null,
        sink: {
            audio: null,
            video: null
        }
    };
    addIceListeners(peerId);
    initRecording(peerId);
    peers[peerId].connection.createOffer().then((offer) => peers[peerId].connection.setLocalDescription(offer)).then(() => {
        signalingChannel.send(JSON.stringify({
            action: 'record',
            peer: peerId,
            offer: peers[peerId].connection.localDescription
        }));
    });
}

function addIceListeners(peerId){
    let connection = peers[peerId].connection;
    connection.addEventListener('icecandidate', (e) => {
        if(e.candidate)
            signalingChannel.send(JSON.stringify({
                action: 'candidate',
                id: peerId,
                candidate: e.candidate
            }));
    });
    connection.addEventListener('icecandidateerror', (e) => {
        console.error('ICE error:', e);
    });
    connection.addEventListener('icegatheringstatechange', (e) => {
        let ice = e.target;
        if(ice.iceGatheringState == 'complete' && peers[peerId].pendingSdp != null){
            signalingChannel.send(JSON.stringify(peers[peerId].pendingSdp));
            peers[peerId].pendingSdp = null;
        }
    });
}

function initStream(peerId){
    let connection = peers[peerId].connection;
    peers[peerId].sink.audio = new RTCAudioSink(connection.addTransceiver('audio').receiver.track);
    peers[peerId].stream = {
        recordPath: `${VIDEO_INPUT_DIR}/${peerId}`,
        size: null,
        video: null,
        audio: new PassThrough()
    };
    peers[peerId].sink.audio.addEventListener('data',  ({samples: {buffer}}) => {
        if(peers[peerId].audioOnly && !peers[peerId].stream.proc)
            initPeerRecording(peerId);
        peers[peerId].stream.audio.push(Buffer.from(buffer));
    });
}

function enableVideo(peerId){
    let connection = peers[peerId].connection, lastFrame, frames = [];
    peers[peerId].stream.video = new PassThrough();
    peers[peerId].sink.video = new RTCVideoSink(connection.addTransceiver('video').receiver.track);

    peers[peerId].sink.video.addEventListener('frame', ({frame: {width, height, data}}) => {
        lastFrame = data;
        frames.push(lastFrame);
        if(!peers[peerId].stream.size){
            peers[peerId].stream.size = width + 'x' + height;
            peers[peerId].stream.recordPath += '-[timestamp].mp4';
        }
        if(!peers[peerId].audioOnly && !peers[peerId].stream.proc){
            initPeerRecording(peerId);
            let interval = setInterval(() => {
                frames.forEach((frame) => {
                    peers[peerId].stream.video.push(Buffer.from(frame));
                });
                let lostFrames = 30 - frames.length;
                if(lostFrames > 0)
                    for(let i = 0; i < lostFrames; i++)
                        peers[peerId].stream.video.push(Buffer.from(lastFrame));
                frames = [];
                if(peers[peerId].disconnected)
                    clearInterval(interval);
            }, 1000);
        }
    });
}

function initPeerRecording(peerId){
    let stream = peers[peerId].stream;
    stream.recordPath = stream.recordPath.replace('[timestamp]', Math.floor(Date.now() / 1000));
    stream.proc = ffmpeg().addInput((new StreamInput(stream.audio)).url)
        .addInputOptions([
            '-f s16le',
            '-ar 48k'
        ]);
    if(!peers[peerId].audioOnly)
        stream.proc.addInput((new StreamInput(stream.video)).url)
            .addInputOptions([
                '-f', 'rawvideo',
                '-pix_fmt', 'yuv420p',
                '-s', stream.size,
                '-r', '30',
            ]);
    stream.proc.on('start', () => {
        console.log('Started recording to ', stream.recordPath)
    }).on('end', () => {
        console.log('Finished recording to ', stream.recordPath)
    }).size(VIDEO_OUTPUT_SIZE).output(stream.recordPath).run();
}

function initRecording(peerId){
    initStream(peerId);
    if(peers[peerId].audioOnly)
        peers[peerId].stream.recordPath += '-[timestamp].mp3';
    else
        enableVideo(peerId);
}

function peerDisconnected(peerId){
    if(peers[peerId].terminate !== undefined)
        return;
    peers[peerId].sink.audio.stop();
    peers[peerId].terminate = setInterval(() => {
        let channels = ['audio', 'video'], bytes = {audio: 0, video: 0}, audioOnly = peers[peerId].audioOnly;
        for(let i in channels)
            if(peers[peerId].stream[channels[i]])
                bytes[channels[i]] = peers[peerId].stream[channels[i]].readableLength;
        if((!audioOnly && bytes.video == 0) || (audioOnly && bytes.audio == 0)){
            clearInterval(peers[peerId].terminate);
            terminateRecording(peerId);
        }
    }, 1000);
    peers[peerId].disconnected = true;
}

function terminateRecording(peerId){
    if(!peers[peerId].audioOnly)
        peers[peerId].sink.video.stop();
    if(peers[peerId].stream.audio)
        peers[peerId].stream.audio.end();
    if(peers[peerId].stream.video)
        peers[peerId].stream.video.end();
    peers[peerId].stream.end = true;
}

// Checks if all peers went offline to merge their recordings before successfully terminating the process.
let peersLoop = setInterval(() => {
    let peersCount = Object.keys(peers).length, offlineCount = 0;
    if(peersCount == 0)
        return;
    for(var id in peers)
        if(peers[id].stream && peers[id].stream.end)
            offlineCount++;
    if(offlineCount == peersCount){
        clearInterval(peersLoop);
        process.exit();
    }
}, 1000);

// Starts the recording service for the given room.
axios.get(process.env['ICE_API_URL']).then((response) => {
    if(!fs.existsSync(VIDEO_INPUT_DIR))
        fs.mkdirSync(VIDEO_INPUT_DIR, {recursive: true});
    iceServers = response.iceServers;
    initSignalingChannel();
}).catch((error) => console.log(error));